name: Security Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-review:
    name: Run security review
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Claude security review
        uses: anthropics/claude-code-security-review@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
